export channel_language="Your_channel_language"
export channel_name="Your_channel_name"
export channel_theme="Your_channel_theme"
export channel_url="https://t.me/channel_url"
export bot_token="your_bot_token"
